2024-12-14 14:10:45,037 - INFO - Application started
2024-12-14 14:10:47,950 - INFO - ----------Processing loop started----------
2024-12-14 14:10:47,950 - INFO - ----New round of detections----
2024-12-14 14:10:48,472 - INFO - The data of objects: []
2024-12-14 14:10:48,580 - INFO - ----New round of detections----
2024-12-14 14:10:49,038 - INFO - The data of objects: []
2024-12-14 14:10:49,148 - INFO - ----New round of detections----
2024-12-14 14:10:49,554 - INFO - The data of objects: []
2024-12-14 14:10:49,665 - INFO - ----New round of detections----
2024-12-14 14:10:50,106 - INFO - The data of objects: []
2024-12-14 14:10:50,219 - INFO - ----New round of detections----
2024-12-14 14:10:50,698 - INFO - The data of objects: []
2024-12-14 14:10:50,813 - INFO - ----New round of detections----
2024-12-14 14:10:51,221 - INFO - The data of objects: []
2024-12-14 14:10:51,331 - INFO - ----New round of detections----
2024-12-14 14:10:51,737 - INFO - The data of objects: []
2024-12-14 14:10:51,847 - INFO - ----New round of detections----
2024-12-14 14:10:52,341 - INFO - The data of objects: []
2024-12-14 14:10:52,454 - INFO - ----New round of detections----
2024-12-14 14:10:52,850 - INFO - The data of objects: []
2024-12-14 14:10:52,956 - INFO - ----New round of detections----
2024-12-14 14:10:53,375 - INFO - The data of objects: []
2024-12-14 14:10:53,487 - INFO - ----New round of detections----
2024-12-14 14:10:53,876 - INFO - The data of objects: []
2024-12-14 14:10:53,990 - INFO - ----New round of detections----
2024-12-14 14:10:54,394 - INFO - The data of objects: []
2024-12-14 14:10:54,504 - INFO - ----New round of detections----
2024-12-14 14:10:54,916 - CRITICAL - Critical error in while loop
Traceback (most recent call last):
  File "c:\Users\User\OneDrive - Afeka College Of Engineering\שולחן העבודה\final Project - Eye sight\code\main_with_gui.py", line 285, in processing_loop
    radar_display.update_display(radar_objects)
  File "c:\Users\User\OneDrive - Afeka College Of Engineering\שולחן העבודה\final Project - Eye sight\code\OOP_GUI_radar.py", line 58, in update_display
    self.canvas.draw()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\matplotlib\backends\backend_tkagg.py", line 11, in draw
    self.blit()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\matplotlib\backends\backend_tkagg.py", line 14, in blit
    _backend_tk.blit(self._tkphoto, self.renderer.buffer_rgba(),
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\matplotlib\backends\_backend_tk.py", line 119, in blit
    photoimage.tk.call(_blit_tcl_name, argsid)
_tkinter.TclError
2024-12-14 14:10:54,942 - INFO - ----New round of detections----
